### ISSUE TITLE
Criticisms

### ISSUE THREAD

**Issue by edoss00** [kazijamal/TwoFortyNine_jamalK-lauE-leeR#3]
- It’s not clear how you will measure the positivity/negativity of public media sentiment and Trump tweets, since the datasets don’t explicitly label articles as either.  
- Medium Income Data: ?
- You could create a separate section to list all the datasets you will be using instead of spreading them throughout the doc
- Consider using an sqlite database updated whenever new info is present rather than copying large amount of data into a csv and out again
- Transportation Data: it looks like the turnstile data updates weekly; how often will you issue requests/new data, and what system will be in place to do that?
- Elaborate on purpose/function of extra packages

by MarshmallowFlush

**Comment by kazijamal** [comment]
- To measure the positivity/negativity of public media sentiment and Trump tweets, we will be using sentiment analysis and natural processing Python libraries on the datasets.
- We are currently looking for a data source for the Medium Income Data
- We will only process the data once rather than making requests multiple times. We are creating Python utility files to do this processing for us. However, if we finish all of our MVP features, we will attempt to create a GitHub Actions script that will run our processing file every weekend and update our CSV.

Thank you for the constructive feedback!

-- Team TwoFortyNine :: Kazi Jamal, Eric Lau, and Raymond Lee

**Comment by tofr** [comment]
This is nice. Specific, actionable. Remember, if GH action scripts gets incorporated, we will need a QAF how-to... so far, I think the closest we have is this mention:
https://groups.google.com/a/stuy.edu/d/msg/softdev19-20/l7WY_S7GG34/e0HyurYIAQAJ
